# Generated by Django 3.0.6 on 2020-07-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200706_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='imgfile',
        ),
    ]
