# Generated by Django 3.0.6 on 2020-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200706_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='author',
        ),
    ]
