# Generated by Django 3.0.6 on 2020-07-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200706_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='authorview',
            name='a_name',
        ),
    ]
