# Generated by Django 3.0.6 on 2020-07-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200706_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorview',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.AuthorName'),
        ),
    ]
