# Generated by Django 3.0.6 on 2020-07-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorview',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
