# Generated by Django 3.0.6 on 2020-07-10 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_authorview_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.Image'),
            preserve_default=False,
        ),
    ]
