# Generated by Django 3.0.6 on 2020-07-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200710_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='time_added',
        ),
    ]
