# Generated by Django 3.0.6 on 2020-07-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_story_time_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
