# Generated by Django 3.0.6 on 2020-07-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_story_time_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='time_added',
        ),
    ]
