# Generated by Django 3.0.6 on 2020-07-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_story_time_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
