# Generated by Django 3.0.6 on 2020-07-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ArticleCategory')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.AuthorName')),
            ],
        ),
    ]
