# Generated by Django 3.0.6 on 2020-07-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_authorview_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorview',
            name='content',
        ),
    ]
